/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:12884ff9-4a5c-4a5f-b42c-280c81cadb33",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_fiL3OM8eI",
    "aws_user_pools_web_client_id": "3uh2rbbi93fibvdoti9dgkubee",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "eu-north-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "itemsdb-dev",
            "region": "eu-north-1"
        },
        {
            "tableName": "cart-dev",
            "region": "eu-north-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "shop",
            "endpoint": "https://8vwfsc2nlb.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        }
    ]
};


export default awsmobile;